apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: core
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: system
  labels:
    control-plane: core
spec:
  selector:
    matchLabels:
      control-plane: core
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: core
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
      - emptyDir:
          sizeLimit: 5Mi
        name: package-cache
      containers:
      - command:
        - /core
        args:
        - start
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --cache-dir=/cache
        #- --debug
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_DISCOVERY
          value: ""
        - name: SERVICE_DISCOVERY_NAMESPACE
          value: ""
        - name: SERVICE_DISCOVERY_DCNAME
          value: ""
        volumeMounts:
        - mountPath: /cache
          name: package-cache
        image: yndd/nddcore:latest
        #imagePullPolicy: Always
        name: core
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 100m
            memory: 100Mi
      serviceAccountName: core
      terminationGracePeriodSeconds: 10
      
