apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: rbac
  name: rbac-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: rbac
