# permissions for end users to view controllerconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllerconfig-viewer-role
rules:
- apiGroups:
  - pkg.ndd.yndd.io
  resources:
  - controllerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pkg.ndd.yndd.io
  resources:
  - controllerconfigs/status
  verbs:
  - get
