# permissions for end users to edit locks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lock-editor-role
rules:
- apiGroups:
  - pkg.ndd.yndd.io
  resources:
  - locks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.ndd.yndd.io
  resources:
  - locks/status
  verbs:
  - get
