# permissions for end users to edit revisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: revision-editor-role
rules:
- apiGroups:
  - pkg.ndd.yndd.io
  resources:
  - revisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pkg.ndd.yndd.io
  resources:
  - revisions/status
  verbs:
  - get
